<?php
declare(strict_types=1);

/** @var $block \Magento\ReCaptchaUi\Block\ReCaptcha */

/** @var $viewModel \MageSuite\ExtendedRecaptcha\ViewModel\ReCaptcha */
$viewModel = $block->getViewModel();
$recaptchaFor = $block->getRecaptchaFor();
$isInvisibleRecaptcha = $viewModel->isInvisibleRecaptcha($recaptchaFor);
?>

<div class="cs-google-recaptcha cs-google-recaptcha--<?= $recaptchaFor ?>">
    <div class="field-recaptcha cs-google-recaptcha__badge <?= $isInvisibleRecaptcha ? 'cs-google-recaptcha__badge--invisible' : '';?>" id="<?= /* @noEscape */ $block->getRecaptchaId() ?>-container" data-bind="scope:'<?= /* @noEscape */ $block->getRecaptchaId() ?>'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <?php if ($isInvisibleRecaptcha && $viewModel->isRecaptchaCustomNoteEnabled()): ?>
    <span class="cs-google-recaptcha__note">
        <?= $viewModel->getRecaptchaNote();?>
    </span>
    <?php endif; ?>
</div>

<script type="text/x-magento-init">
{
    "#<?= /* @noEscape */ $block->getRecaptchaId() ?>-container": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    }
}
</script>

