<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var $block \Magento\ReCaptchaUi\Block\ReCaptcha */

/** @var $viewModel \MageSuite\ExtendedRecaptcha\ViewModel\ReCaptcha */
$viewModel = $block->getViewModel();
?>

<div class="cs-google-recaptcha-note cs-google-recaptcha-note--<?= $block->getRecaptchaFor() ?>">
    <div class="field-recaptcha" id="<?= /* @noEscape */ $block->getRecaptchaId() ?>-container" data-bind="scope:'<?= /* @noEscape */ $block->getRecaptchaId() ?>'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <?php if ($viewModel->getRecaptchaNote()): ?>
    <span class="cs-google-recaptcha-note__text">
        <?= $viewModel->getRecaptchaNote();?>
    </span>
    <?php endif; ?>
</div>

<script type="text/x-magento-init">
{
    "#<?= /* @noEscape */ $block->getRecaptchaId() ?>-container": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    }
}
</script>

